development:
  host: '127.0.0.1'
  port: 9042
  keyspace: cassy_development

test:
  host: '127.0.0.1'
  port: 9042
  keyspace: cassy_test

production:
  hosts:
    - '107.170.180.21'
  port: 9160
  keyspace: cassy_production
  # username: 'myappuser'
  # password: 'password1'
